### ISSUE TITLE
I would like to try this! the dropbox link doesn't work anymore.

### ISSUE THREAD

**Issue by diegopau** [robermann/aware-at-pc#1]
Could it be possible to reupload it or maybe upload it to the Releases section of the Github repo?

**Comment by robermann** [comment]
Hello,
you can download it from this link
<https://www.dropbox.com/scl/fi/xxb3f2am2wbhg3ebizubs/Aware-pc.exe?rlkey=9gxkdizyz3gjqm76z1ti5jw7e&dl=0>.

**Comment by robermann** [comment]
link fixed on README

**Comment by diegopau** [comment]
Thanks!
